"""Render docs/m2-results.md from reports/m2/results.json (+ the first held-out run). Numbers are copied, never typed; the analysis text sits beside them."""
import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
R = json.loads((ROOT / "reports/m2/results.json").read_text())
F = json.loads((ROOT / "reports/m2/results-first-run.json").read_text())
ST = ("lexical", "vector", "hybrid", "rerank")
NAME = {"lexical": "A lexical (FTS)", "vector": "B vector (pgvector)", "hybrid": "C hybrid (RRF)", "rerank": "D hybrid + rerank"}
H, D = R["heldout"], R["dev"]
f = lambda x: "–" if x is None else (f"{x:.2f}" if isinstance(x, float) else str(x))  # noqa: E731
pct = lambda x: "–" if x is None else f"{round(100 * x)}%"  # noqa: E731


def row(label, vals):
    return f"| {label} | " + " | ".join(vals) + " |"


def table(head, rows):
    return "\n".join([row(head[0], head[1:]), "|" + "---|" * len(head), *rows])


def failures(s):
    out = []
    for x in H[s]["rows"]:
        k = None
        if x["sufficiency"] == "sufficient":
            if not x["hit@5"]:
                k = "ranking miss (no authoritative doc in top 5)"
            elif x["outcome"] == "NO_SUFFICIENT_EVIDENCE":
                k = "wrongly abstained (confidence below dev-tuned threshold)"
            elif x["outcome"] == "CONFLICTING_AUTHORITATIVE_EVIDENCE":
                k = "false conflict"
            elif not x["governed_hit"]:
                k = "evidence returned but authoritative doc not among the cited items"
        elif x["sufficiency"] == "insufficient" and x["outcome"] == "EVIDENCE":
            k = "FALSE CONFIDENCE (evidence returned for an unanswerable question)"
        elif x["sufficiency"] == "conflicting" and x["outcome"] != "CONFLICTING_AUTHORITATIVE_EVIDENCE":
            k = f"conflict missed ({x['outcome']})"
        if k:
            out.append((x["ticket_id"], x["slice"], k))
    return out


def counts(s):
    c = {}
    for _, _, k in failures(s):
        c[k.split(" (")[0]] = c.get(k.split(" (")[0], 0) + 1
    return c


M = R["meta"]
md = []
w = md.append
w(f"""# M2 results: retrieval, evidence and evaluation

*Generated by `scripts/render_m2_report.py` from `reports/m2/results.json` (code SHA at run time `{M['git_sha'][:7]}`, mode `{M['mode']}`). Nothing below is typed by hand except the analysis text.*

## What was measured, and what it is worth
- **Held-out set**: {M['heldout_tickets']} tickets, **hand-labelled by a single AI reviewer (Claude), in one session, not independent human annotation** (see `data/hand-labelled-v1/RUBRIC.md`). Frozen by hash before any strategy was scored (`docs/eval-freeze.json`, enforced by a test).
- **Dev set**: {M['dev_tickets']} generator tickets with the generator's own answer key (`synthetic_label`; circular, templated). Used only to choose parameters.
- Small n (25 answerable / 11 unanswerable / 4 conflicting held-out tickets): differences between strategies are **descriptive**; 95% bootstrap intervals are given and mostly overlap.
- Corpus: {M['documents']} runbooks → {M['chunks']} chunks (every document fits one chunk; chunking is structure-aware but trivial on this corpus). Embedding model `{M['embedding_model']}` ({M['embedding_dim']}-d), reranker `{M['reranker']}`, PostgreSQL {M['postgres']}, pgvector {M['pgvector']}, RRF k={M['rrf_k']}, query prefix {'on' if M['query_prefix'] else 'off'} (chosen on dev).
- Metrics are document-level. "Hit/MRR/Recall" use the **raw** ranking (all lifecycle states, before governance); "citation precision", outcomes and forbidden-evidence use the **governed** output.

## 1. Headline (held-out, hand labels)
""")
rows = []
for s in ST:
    h = H[s]["summary"]
    rows.append(row(NAME[s], [f(h["hit@1"]) + f" [{H[s]['hit@1_ci95'][0]:.2f}–{H[s]['hit@1_ci95'][1]:.2f}]", f(h["hit@3"]), f(h["hit@5"]) + f" [{H[s]['hit@5_ci95'][0]:.2f}–{H[s]['hit@5_ci95'][1]:.2f}]",
                         f(h["mrr@10"]) + f" [{H[s]['mrr_ci95'][0]:.2f}–{H[s]['mrr_ci95'][1]:.2f}]", f(h["recall@5"]), f(h["citation_precision"]), pct(h["governed_success_on_sufficient"])]))
w(table(["strategy (n=25 answerable)", "Hit@1 [95% CI]", "Hit@3", "Hit@5 [95% CI]", "MRR@10 [95% CI]", "Recall@5", "citation precision", "governed success"], rows))
w("\n*governed success = outcome EVIDENCE and an authoritative document among the cited top-3 items. Citation precision is computed only over items a strategy actually cited, so a strategy that abstains a lot can look precise; cited items on answerable tickets: " + ", ".join(f"{NAME[s]}: {sum(len(x['cited']) for x in H[s]['rows'] if x['sufficiency'] == 'sufficient')}" for s in ST) + ".*\n")
w("## 2. Dev vs held-out: the synthetic set flatters every strategy\n")
rows = []
for s in ST:
    rows.append(row(NAME[s], [f(D[s]["summary"]["hit@1"]), f(H[s]["summary"]["hit@1"]), f(D[s]["summary"]["mrr@10"]), f(H[s]["summary"]["mrr@10"]), f(D[s]["summary"]["confidence_auc_sufficient_vs_insufficient"]), f(H[s]["summary"]["confidence_auc_sufficient_vs_insufficient"])]))
w(table(["strategy", "dev Hit@1", "held-out Hit@1", "dev MRR", "held-out MRR", "dev confidence AUC", "held-out confidence AUC"], rows))
w("")
DT = json.loads((ROOT / "docs/m2-dev-tuning.json").read_text())["thresholds"]
med = lambda s_, k: statistics.median([x["confidence"] for x in H[s_]["rows"] if x["sufficiency"] == k and x["confidence"] is not None])  # noqa: E731
rows = [row(NAME[s_], [f"{DT[s_]['threshold']}", f"{DT[s_]['median_conf_sufficient']} / {DT[s_]['median_conf_insufficient']}", f"{med(s_, 'sufficient'):.3f} / {med(s_, 'insufficient'):.3f}"]) for s_ in ST]
w(table(["strategy", "dev-tuned threshold", "dev median top confidence: answerable / unanswerable", "held-out: answerable / unanswerable"], rows))
w("""
Held-out tickets are longer (median 161 characters vs 98 on dev); confidence distributions shift in both directions: answerable tickets score lower, unanswerable ones higher.

*Confidence AUC* = probability that an answerable ticket's top retrieval confidence exceeds an unanswerable one's (0.5 = no signal). It is threshold-free, so it shows that the failure of abstention below is **not just a bad threshold**: on templated dev tickets the confidence separates answerable from unanswerable almost perfectly, on free-language held-out tickets it barely does (held-out has only 11 unanswerable tickets, so the AUC is noisy, but all four sit near 0.5–0.66).
""")
w("## 3. By slice (held-out; Hit@5 / MRR@10 on answerable tickets; n per slice is 3–10)\n")
sl_names = ["routine", "terminology", "stale", "near_duplicate", "distractor"]
rows = []
for sl in sl_names:
    rows.append(row(f"{sl} (n={H['lexical']['by_slice'][sl]['n_sufficient']})", [f"{f(H[s]['by_slice'][sl]['hit@5'])} / {f(H[s]['by_slice'][sl]['mrr@10'])}" for s in ST]))
w(table(["slice", *[NAME[s] for s in ST]], rows))
w("\n### Outcome distribution per slice (governed): E=EVIDENCE, N=NO_SUFFICIENT_EVIDENCE, C=CONFLICTING_AUTHORITATIVE_EVIDENCE\n")
abbr = {"EVIDENCE": "E", "NO_SUFFICIENT_EVIDENCE": "N", "CONFLICTING_AUTHORITATIVE_EVIDENCE": "C"}
rows = []
for sl in ["routine", "terminology", "stale", "near_duplicate", "distractor", "conflicting", "evidence_gap", "injection_exposure"]:
    cells = []
    for s in ST:
        o = H[s]["by_slice"][sl]["outcomes"]
        cells.append(" ".join(f"{abbr[k]}{v}" for k, v in sorted(o.items())))
    exp = {"conflicting": "C", "evidence_gap": "N", "injection_exposure": "N"}.get(sl, "E")
    rows.append(row(f"{sl} (n={H['lexical']['by_slice'][sl]['n']}, correct = {exp})", cells))
w(table(["slice", *[NAME[s] for s in ST]], rows))
w("\n## 4. Abstention, false confidence and conflicts (held-out)\n")
rows = []
for s in ST:
    h = H[s]["summary"]
    rows.append(row(NAME[s], [pct(h["abstained_on_insufficient"]), pct(h["false_confidence_on_insufficient"]), pct(h["wrongly_abstained_on_sufficient"]), pct(h["conflict_detected_on_conflicting"]), pct(h["wrongly_conflict_on_sufficient"])]))
w(table(["strategy", "abstained on unanswerable (n=11) ✔", "FALSE CONFIDENCE on unanswerable ✘", "wrongly abstained on answerable (n=25) ✘", "conflict detected (n=4) ✔", "false conflict on answerable ✘"], rows))
w("\n## 5. Lifecycle, duplicates and injected documents (held-out, 40 tickets)\n")
rows = []
for s in ST:
    h = H[s]["summary"]
    rows.append(row(NAME[s], [pct(h["raw_top5_superseded_or_draft_rate"]), str(h["governed_superseded_or_draft_count"]), str(h["raw_top5_has_injected_doc"]), str(h["governed_adversarial_returned"])]))
w(table(["strategy", "tickets whose RAW top-5 holds a superseded/draft doc (of relevant tickets)", "superseded/draft docs in GOVERNED evidence", "tickets whose raw top-5 contains an injected doc", "tickets where governed evidence returned an injected doc (3 injection tickets)"], rows))
w("""
Governance removes superseded/draft documents from evidence by construction (0 in the governed output for every strategy, with the exclusions listed in `excluded`). It does **not** remove the injected documents: they are active, and nothing in retrieval decides that their *content* is illegitimate. They come back flagged `instruction_like_text` (advisory) and `content_trust: untrusted_data`; the boundary is that retrieval cannot act on them (section 10).

## 6. resync / re-sync (terminology) under each strategy
The lexical miss is preserved as a baseline (no synonym, stem or rewrite; a mutation test guards that). Rank of the re-sync runbook family for bare queries (null = not in top 10):
""")
rows = []
for text, ranks in R["terminology_probes"]["ranks"].items():
    rows.append(row(f"`{text}`", [str(ranks[s]) for s in ST]))
w(table(["bare query", *[NAME[s] for s in ST]], rows))
w("\nHand-labelled terminology tickets TCK-8011..8016 (first authoritative rank in the raw ranking / governed outcome):\n")
rows = []
for t in range(8011, 8017):
    cells = []
    for s in ST:
        x = next(r for r in H[s]["rows"] if r["ticket_id"] == f"TCK-{t}")
        cells.append(f"{x['first_rank']} / {abbr[x['outcome']]}")
    rows.append(row(f"TCK-{t}", cells))
w(table(["ticket", *[NAME[s] for s in ST]], rows))
w("""
Reading: bare `resync` finds nothing lexically, while `re-sync` is rank 1. In a full ticket the lexical strategy usually still finds the runbook through other words (duplicate, feed, carrier), so the miss shows up as a rank/score loss rather than a failure, except for the pure paraphrase TCK-8016, which lexical misses entirely. Vector/hybrid/rerank retrieve it; hybrid placed TCK-8016 only at rank 6 (RRF averages in a lexical list that does not contain the document).

## 7. Tenant evidence
""")
te = R["tenant_evidence"]
w(f"Open-incident lookup through the signed-scope catalogue: recall {f(te['incident_recall'])} on the {te['n_with_incident_labels']} hand tickets that have incident labels (a very small sample); similar-ticket search returned **{te['similar_ticket_accounts_other_than_case_account']}** tickets from any account other than the case's own across all 40 hand tickets (the DB-level attacks are in `tests/db/test_m2_retrieval.py`).\n")
w("## 8. Latency and resources (live mode only; one laptop, warm, 5 repetitions; NOT a production claim)\n")
if "latency" in R:
    L = R["latency"]
    rows = [row(NAME[s], [f(L[s]["db_and_governance_ms_median"]), f(L[s]["p95"])]) for s in ST]
    w(table(["strategy: database + governance only (query vector already available)", "median ms", "p95 ms"], rows))
    w(f"\nQuery embedding (bge-small, CPU): median {L['query_embedding_ms']['median']} ms, p95 {L['query_embedding_ms']['p95']} ms (n={L['query_embedding_ms']['n']}). Cross-encoder rerank of 20 passages: median {L['rerank_20_passages_ms']['median']} ms, p95 {L['rerank_20_passages_ms']['p95']} ms (n={L['rerank_20_passages_ms']['n']}).")
    r_ = R["resources"]
    w(f"\nResources: embedding model snapshot {r_['embedding_model_mb']} MB; reranker snapshot {r_['reranker_mb']} MB (the snapshot holds several ONNX variants); whole benchmark process peak RSS {r_['peak_rss_mb']} MB (both models loaded); `runbook_chunks` table incl. indexes {r_['pg_total_bytes']['runbook_chunks']} bytes; embedding cache file {r_['embedding_cache_file_mb']} MB. Environment: {M['platform']}, {M['cpu']}, Python {M['python']}. Clean database build + load: {M['clean_db_build_seconds']} s. At 60 chunks these latencies say nothing about scale; the exact (non-indexed) vector scan is only defensible at this size.")
w("""
## 9. Failures (final run), by cause
""")
cats = {s: counts(s) for s in ST}
allk = sorted({k for c in cats.values() for k in c})
rows = [row(k, [str(cats[s].get(k, 0)) for s in ST]) for k in allk]
w(table(["failure type", *[NAME[s] for s in ST]], rows))
w("\nTicket-level failures for **B vector** (the strategy chosen in ADR-0013), for the others see `reports/m2/results.json`:\n")
rows = [row(t, [sl, k]) for t, sl, k in failures("vector")]
w(table(["ticket", "slice", "failure"], rows))
w("""
### Why retrieval fails here (analysis)
1. **Similarity confidence is not an evidence-sufficiency detector.** Unanswerable held-out tickets about, e.g., invoice PDF layout or tax IDs match "look-alike" filler pages (`Invoice PDF layout`, `Tax identifiers on invoices`) almost as well as real answers match theirs. These pages contain no answer, but share the topic words, so every strategy returns them (false confidence). The thresholds that separate the cases on templated dev tickets (AUC ≈ 0.95–1.0) do not transfer to free-language tickets (AUC ≈ 0.55–0.66).
2. **Wrong abstentions are the mirror image**: held-out tickets are longer and free-form (median 161 vs 98 characters); their answerable members score lower than dev's (lexical `ts_rank` median 0.029 → 0.018, rerank logit 3.4 → −1.0) while unanswerable ones score higher (lexical 0.006 → 0.019), so correct, top-ranked documents fall under thresholds calibrated on dev. Vector (cosine) abstained wrongly least (12%) and also has the highest false confidence (55%): consistent with its dev threshold being low relative to this distribution; that explanation was not tested further.
3. **Injected documents are semantically on-topic** for queries about "operations notes", "maintenance mode", "routing tips" (their legitimate-looking headings), so they are retrieved by design of the test and by nature of the documents. Retrieval quality metrics cannot and should not hide them; the controls are architectural.
4. **Stale documents tie with, or closely resemble, current ones**: obsolete runbooks are often identical to the current one apart from a footer (RBK-0046 vs RBK-0020) or differ by one number (RBK-0009 vs RBK-0022), so raw rank order between them is close to arbitrary (stale-slice MRR: lexical 0.38, hybrid 0.46 vs vector 0.88). Lifecycle governance, not ranking, fixes this; ranking cannot know which copy is current.
5. **Vocabulary mismatch** is a lexical failure (re-sent vs retry, reload connection vs re-sync). Hybrid fusion with equal weights inherits it; hybrid ranked below vector on both dev and held-out here (weighted fusion was not tried: more tuning on a small dev set).
6. **Near-duplicate copies** inflate or split ranked lists; collapsing them in governance (and counting any copy as a hit) removes this.
7. **Conflicts are found by corpus metadata, not by ranking**: the two conflict pairs (retries 30 attempts/30 h vs 20/90 h; slot 45 vs 10 minutes) raise CONFLICTING_AUTHORITATIVE_EVIDENCE when one member is in the top 3 and confidence is above threshold. Lexical and hybrid each missed one of four conflicting tickets (TCK-8018): a member of the pair was retrieved (lexical rank 3, hybrid rank 1) but top confidence was under the abstention threshold, which is checked before conflicts, so the outcome was NO_SUFFICIENT_EVIDENCE. Abstain-before-conflict is therefore a questionable ordering; it was not changed after seeing held-out results.

## 10. Untrusted retrieved text: what is and is not demonstrated
Tested against real PostgreSQL (`tests/db/test_m2_retrieval.py`; attacks A-I1-11, A-I2-30, A-I3-06, A-I4-07): all four injected runbooks (RBK-0030, 0032, 0035, 0051) are actually retrieved by adversarial queries; they come back as `content_trust: untrusted_data` with an advisory flag (a regex, not the boundary); the case scope, its signed settings and the database state are unchanged afterwards; the application role cannot write; the result schema has no field that could carry a tool, approval, scope or workflow change; the retrieval package imports no email/network/subprocess module; planted canary secrets appear in neither output nor logs; no other account's id appears in results produced under a case scope.

**Not demonstrated, because it does not exist yet:** that a model, or the approval/action workflow (M3-M4), ignores an instruction inside retrieved text. M2 shows only that retrieval itself has no capability to act on it.

## 11. Change history of this run (disclosure)
- First held-out run: `reports/m2/results-first-run.json` (code before the governance fix; also before the harness fix that gave tenant-evidence lookups a real case row, so its `incident_recall` of 0.0 was a harness bug, not a retrieval result).
- A unit test then showed the near-duplicate grouping ignored a "(copy)" title suffix, so one of three identical rate-limit runbooks was not collapsed. This was fixed in governance; thresholds were re-tuned on dev (unchanged); the held-out *ranking* numbers did not change, only governed citation precision. First vs final citation precision (held-out):
""")
rows = [row(NAME[s], [f(F["heldout"][s]["summary"]["citation_precision"]), f(H[s]["summary"]["citation_precision"])]) for s in ST]
w(table(["strategy", "first run", "final"], rows))
w("""
- No retrieval parameter, threshold or label was changed after seeing held-out results. The held-out failures above are reported, not fixed.
""")
(ROOT / "docs" / "m2-results.md").write_text("\n".join(md) + "\n")
print("wrote docs/m2-results.md")
