"""Render docs/m2-conflict-order-rerun.md: the published M2 results (abstain-first) next to the same frozen benchmark re-run with conflict-first control order.
Both come from committed result files; nothing is typed by hand."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OLD = json.loads((ROOT / "reports/m2/results.json").read_text())
NEW = json.loads((ROOT / "reports/m2-m3-rerun/results.json").read_text())
ST = ("lexical", "vector", "hybrid", "rerank")
KEYS = [("hit@5", "Hit@5"), ("mrr@10", "MRR@10"), ("citation_precision", "citation precision"), ("governed_success_on_sufficient", "governed success (answerable)"),
        ("wrongly_abstained_on_sufficient", "wrongly abstained (answerable)"), ("wrongly_conflict_on_sufficient", "false conflict (answerable)"),
        ("abstained_on_insufficient", "abstained (unanswerable)"), ("false_confidence_on_insufficient", "false confidence (unanswerable)"), ("conflict_detected_on_conflicting", "conflict detected (conflicting)")]
f = lambda x: "–" if x is None else f"{x:.2f}"  # noqa: E731
out = ["# M2 benchmark re-run after the control-order correction (M3)", "",
       "*Generated by `scripts/render_m3_conflict_order.py`.* The published M2 report ([`m2-results.md`](m2-results.md), `reports/m2/results.json`) is **unchanged** and is reproduced by `--control-order abstain_first`. "
       "This file is the same frozen benchmark (same hand set, same dev set, same caches, same thresholds, nothing retuned) with the corrected order: **a known conflict between active documents among the top-3 is reported before the abstention check**. "
       "That is also the order the frozen protocol (`docs/eval-protocol.md` steps 3–4) specifies; the M2 code had them the other way round.", "",
       "Ranking metrics (Hit@K, MRR, Recall@K) are computed on the raw ranking and are **identical** in both runs. Changed values below are published → corrected.", ""]
for part, title in (("heldout", "Held-out (hand labels, n=40)"), ("dev", "Dev (generator labels, n=300)")):
    out += [f"## {title}", "", "| metric | " + " | ".join(ST) + " |", "|---|" + "---|" * len(ST)]
    for k, lab in KEYS:
        cells = []
        for s in ST:
            a, b = OLD[part][s]["summary"][k], NEW[part][s]["summary"][k]
            cells.append(f(a) if a == b else f"{f(a)} → **{f(b)}**")
        out.append(f"| {lab} | " + " | ".join(cells) + " |")
    out.append("")
out += ["## What changed, in words",
        "- **Conflict detection on the 4 conflicting held-out tickets: lexical and hybrid 3/4 → 4/4** (TCK-8018 was masked by abstention). Vector and rerank were already 4/4.",
        "- **Cost:** a conflict is now reported whenever a member of a conflicting pair is among the top-3 active matches, even when the ticket is unrelated or the match is weak. So some tickets that previously ended in `NO_SUFFICIENT_EVIDENCE` now end in `CONFLICTING_AUTHORITATIVE_EVIDENCE` (abstention on unanswerable tickets falls for every strategy; false conflicts on answerable tickets rise to 4–12% held-out). `EVIDENCE` outcomes on unanswerable tickets (false confidence) are unchanged.",
        "- Why this direction is accepted: hiding a conflict is the unsafe error; surfacing one costs a human look. From M3 on, a CONFLICT outcome is treated by the policy engine as *escalate to a human*, never as authorisation. Nothing was retuned; thresholds and all other parameters are as published.",
        "- Headline decision unchanged: ADR-0013 stands (vector + governance default; lexical as provisioning fallback)."]
(ROOT / "docs/m2-conflict-order-rerun.md").write_text("\n".join(out) + "\n")
print("wrote docs/m2-conflict-order-rerun.md")
